module.exports = {
  COLLISION_GROUPS_NUMBER: 16,
  LAYERS_NUMBER: 10,
  DEFAULT_SCALE: 1 / 70,
  AUTO_ID_PREFIX: "Entity ",
  SHAPE_MIN_SIZE: 0.5,
  TIME_STEP: 60,

  POSITION_TOP_LEFT: [-1, -1],
  POSITION_TOP: [0, -1],
  POSITION_TOP_RIGHT: [1, -1],
  POSITION_RIGHT: [1, 0],
  POSITION_BOTTOM_RIGHT: [1, 1],
  POSITION_BOTTOM: [0, 1],
  POSITION_BOTTOM_LEFT: [-1, 1],
  POSITION_LEFT: [-1, 0],
};